DROP TABLE IF EXISTS cashier_stores;
DROP TABLE IF EXISTS cashiers;
DROP TABLE IF EXISTS admins;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS stores;
